const request = require('request');

module.exports.config = {
    name: 'rname',
    version: '1.0.0',
    credit: 'YourName',
    description: 'Đổi biệt danh Random ',
    usage: '!rname '
  };
  
  module.exports.run = async function (api, event, args, client) {
    // Check if the thread exists before attempting to change the user nickname
    

    const countryCodes = [
        { code: "afk", full: "Afrikaans" },
        { code: "afr", full: "African" },
        { code: "aka", full: "Akan" },
        { code: "alb", full: "Albanian" },
        { code: "alg", full: "Algonquin" },
        { code: "ame", full: "Indigenous American" },
        { code: "amem", full: "New World Mythology" },
        { code: "amh", full: "Amharic" },
        { code: "anci", full: "Ancient" },
        { code: "apa", full: "Apache" },
        { code: "ara", full: "Arabic" },
        { code: "arm", full: "Armenian" },
        { code: "asm", full: "Assamese" },
        { code: "ast", full: "Asturian" },
        { code: "astr", full: "Astronomy" },
        { code: "aus", full: "Indigenous Australian" },
        { code: "ava", full: "Avar" },
        { code: "aym", full: "Aymara" },
        { code: "aze", full: "Azerbaijani" },
        { code: "bal", full: "Balinese" },
        { code: "bas", full: "Basque" },
        { code: "bel", full: "Belarusian" },
        { code: "ben", full: "Bengali" },
        { code: "ber", full: "Berber" },
        { code: "bhu", full: "Bhutanese" },
        { code: "bibl", full: "Biblical (All)" },
        { code: "bos", full: "Bosnian" },
        { code: "bre", full: "Breton" },
        { code: "bsh", full: "Bashkir" },
        { code: "bul", full: "Bulgarian" },
        { code: "bur", full: "Burmese" },
        { code: "cat", full: "Catalan" },
        { code: "cela", full: "Ancient Celtic" },
        { code: "celm", full: "Celtic Mythology" },
        { code: "cew", full: "Chewa" },
        { code: "cha", full: "Chamorro" },
        { code: "che", full: "Chechen" },
        { code: "chi", full: "Chinese" },
        { code: "chk", full: "Cherokee" },
        { code: "cht", full: "Choctaw" },
        { code: "chy", full: "Cheyenne" },
        { code: "cir", full: "Circassian" },
        { code: "cmr", full: "Comorian" },
        { code: "com", full: "Comanche" },
        { code: "cop", full: "Coptic" },
        { code: "cor", full: "Cornish" },
        { code: "cre", full: "Cree" },
        { code: "cro", full: "Croatian" },
        { code: "crs", full: "Corsican" },
        { code: "cze", full: "Czech" },
        { code: "dan", full: "Danish" },
        { code: "dgs", full: "Dagestani" },
        { code: "dhi", full: "Dhivehi" },
        { code: "dut", full: "Dutch" },
        { code: "egya", full: "Ancient Egyptian" },
        { code: "egym", full: "Egyptian Mythology" },
        { code: "eng", full: "English" },
        { code: "enga", full: "Anglo-Saxon" },
        { code: "esp", full: "Esperanto" },
        { code: "est", full: "Estonian" },
        { code: "eth", full: "Ethiopian" },
        { code: "ewe", full: "Ewe" },
        { code: "fae", full: "Faroese" },
        { code: "fairy", full: "Fairy" },
        { code: "fij", full: "Fijian" },
        { code: "fil", full: "Filipino" },
        { code: "fin", full: "Finnish" },
        { code: "fle", full: "Flemish" },
        { code: "fntsg", full: "Gluttakh" },
        { code: "fntsm", full: "Monstrall" },
        { code: "fntsr", full: "Romanto" },
        { code: "fntss", full: "Simitiq" },
        { code: "fntst", full: "Tsang" },
        { code: "fntsx", full: "Xalaxxi" },
        { code: "fre", full: "French" },
        { code: "fri", full: "Frisian" },
        { code: "ful", full: "Fula" },
        { code: "gaa", full: "Ga" },
        { code: "gal", full: "Galician" },
        { code: "gan", full: "Ganda" },
        { code: "geo", full: "Georgian" },
        { code: "ger", full: "German" },
        { code: "gmca", full: "Ancient Germanic" },
        { code: "goth", full: "Goth" },
        { code: "gre", full: "Greek" },
        { code: "grea", full: "Ancient Greek" },
        { code: "grem", full: "Greek Mythology" },
        { code: "grn", full: "Greenlandic" },
        { code: "gua", full: "Guarani" },
        { code: "guj", full: "Gujarati" },
        { code: "hau", full: "Hausa" },
        { code: "haw", full: "Hawaiian" },
        { code: "hb", full: "Hillbilly" },
        { code: "heb", full: "Hebrew" },
        { code: "hin", full: "Hindi" },
        { code: "hippy", full: "Hippy" },
        { code: "hist", full: "History" },
        { code: "hmo", full: "Hmong" },
        { code: "hun", full: "Hungarian" },
        { code: "ibi", full: "Ibibio" },
        { code: "ice", full: "Icelandic" },
        { code: "igb", full: "Igbo" },
        { code: "ind", full: "Indian" },
        { code: "indm", full: "Hindu Mythology" },
        { code: "ing", full: "Ingush" },
        { code: "ins", full: "Indonesian" },
        { code: "inu", full: "Inuit" },
        { code: "iri", full: "Irish" },
        { code: "iro", full: "Iroquois" },
        { code: "ita", full: "Italian" },
        { code: "jap", full: "Japanese" },
        { code: "jav", full: "Javanese" },
        { code: "jer", full: "Jèrriais" },
        { code: "jew", full: "Jewish" },
        { code: "kan", full: "Kannada" },
        { code: "kaz", full: "Kazakh" },
        { code: "khm", full: "Khmer" },
        { code: "kig", full: "Kiga" },
        { code: "kik", full: "Kikuyu" },
        { code: "kk", full: "Kreatyve" },
        { code: "kon", full: "Kongo" },
        { code: "kor", full: "Korean" },
        { code: "kur", full: "Kurdish" },
        { code: "kyr", full: "Kyrgyz" },
        { code: "lao", full: "Lao" },
        { code: "lat", full: "Latvian" },
        { code: "lim", full: "Limburgish" },
        { code: "lite", full: "Literature" },
        { code: "litk", full: "Arthurian Romance" },
        { code: "lth", full: "Lithuanian" },
        { code: "luh", full: "Luhya" },
        { code: "luo", full: "Luo" },
        { code: "mac", full: "Macedonian" },
        { code: "mag", full: "Maguindanao" },
        { code: "mal", full: "Maltese" },
        { code: "man", full: "Manx" },
        { code: "mao", full: "Maori" },
        { code: "map", full: "Mapuche" },
        { code: "vie", full: "Vietnamese" },
        { code: "may", full: "Mayan" },
        { code: "mbu", full: "Mbundu" },
        { code: "medi", full: "Medieval" },
        { code: "mlm", full: "Malayalam" },
        { code: "mly", full: "Malay" },
        { code: "moh", full: "Mohawk" },
        { code: "mon", full: "Mongolian" },
        { code: "morm", full: "Mormon" },
        { code: "yor", full: "Yoruba" },
        { code: "zap", full: "Zapotec" },
        { code: "zul", full: "Zulu" }
    ];

    const gender = [
        { code: "m", full: "Nam" },
        { code: "f", full: "Nữ" },
        { code: "mf", full: "Bê đê" }
    ];
    const rdC = Math.floor(Math.random() * 149);
    const rdG = Math.floor(Math.random() * 3);
    request(`https://www.behindthename.com/api/random.json?usage=${countryCodes[rdC].code}&gender=${gender[rdG].code}&key=mi451266190`, (err, response, body) => {
    if (err) {
        console.error(err);
        return;
    }

    const data = JSON.parse(body);
    console.log(data, `https://www.behindthename.com/api/random.json?usage=${countryCodes[rdC].code}&gender=${gender[rdG].code}&key=mi451266190`);
    api.changeNickname(`${data.names[0]} ${data.names[1]}`, event.threadID, event.senderID);
    
    api.sendMessage({
        body: `Tên đã đổi thuộc quốc gia ${countryCodes[rdC].full} và là tên dành cho ${gender[rdG].full} (～￣▽￣)～`,
        attachment: null,
        mentions: [],
         // Mã màu hồng
    }, event.threadID, event.messageID);
    
});
};
  